function parameter_value = config_walker_o2(parameter_name)
%% parameter_value = config(parameter_name)
% Configuration of file paths and parameters for running TGEM
% Input
%   char parameter_name:        (opt) name of the parameter, whose value should
%                               be returned
%                               if empty or not given, the MATLAB path and
%                               COBRA solver will be set and the value of
%                               parameter_value will be 1.
% Output
%   parameter_value:            value of the requested parameter
%                               the type dependy on the type of parameter
% Philipp Wendering, University of Potsdam (philipp.wendering@gmail.com) 23/03/2023

if ~exist('parameter_name', 'var') || isempty(parameter_name)
    paramFlag = false;
else
    paramFlag = true;
end

%% File paths
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                      |-----------------------|
%                      |  Top-level directory  |
%                      |-----------------------|
%
% Give here the absolute path to the AraTModel directory. The code files will be
% added to the MATLAB path.
pathToTGEM = 'C:\Users\wende\MobaXterm\home\AraTModel';
% add scripts and functions to the MATLAB search path
if ~paramFlag && exist('simulateTempEffects', 'file') ~= 2
    addpath(genpath(fullfile(pathToTGEM, 'code', 'matlab')))
    addpath(fullfile(pathToTGEM, 'code'))
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                          |-------------------|
%                          |  Metabolic model  |
%                          |-------------------|
%
% Path to the metabolic model.
modelFile = fullfile(pathToTGEM, 'metabolic-models', 'AraCore_v2_1.mat');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%            |-----------------------------------------------|
%            |  Model configured for temperature adjustment  |
%            |-----------------------------------------------|
%
% Path to the updated metabolic model that has been configured for
% temperature adjustment using the function "createTGEM".
tgemFile = fullfile(pathToTGEM, 'metabolic-models', 'TGEM.mat');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                       |-------------------------|
%                       |  BRENDA EC number file  |
%                       |-------------------------|
%
% TAB-separated file without colummn headers, with columns
% 1) EC number
% 2) official reaction name
% 3) comment / history
% The file was downloaded from BRENDA on 28/02/2023 and can be updated from
% the BRENDA website:
% click on "classic view" -> click on "EC Number" -> click on "Search"
% -> click on "download all results as CSV"
brendaECFile = fullfile(pathToTGEM, 'translation-tables', 'brenda_ec_numbers_20230228.csv');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                            |-----------------|
%                            |  Meltome Atlas  |
%                            |-----------------|
%
% TAB-separated file that was created using the cross-species Meltome Atlas
% available at https://meltomeatlas.proteomics.wzw.tum.de/master_meltomeatlasapp/
% (Jarzab et al. (2020), DOI: 10.1038/s41592-020-0801-4).
% The file has columns:
% 1) "Protein_ID":      Protein ID as in the Meltome Atlas
%                       (UniProt ID + "_" + gene name)
% 2) "gene_name":       gene name
% 3) "meltPoint":       estimated melting temperature (Jarzab et al. (2020)
% 4) "fold_change":     fraction of non-denatured protein at a given
%                       temperature
% 5) "temperature":     corresponding temperature to "fold_change"
meltomeFile = fullfile(pathToTGEM, 'protein-stability', 'ath-protein-stability.csv');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                            |----------------|
%                            |  UniProt file  |
%                            |----------------|
%
% TAB-separated file downloaded from UniProt, which contains all reviewed
% UniProt entries for A. thaliana. The columns are:
% 1) "Entry"
% 2) "Gene names"
% 3) "Organism"
% 4) "EC number"
% 5) "Temperature dependence"
% 6) "Kinetics"
uniprotFile = fullfile(pathToTGEM, 'translation-tables',...
    'uniprot-arabidopsis-thaliana-revieved.tsv');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                  |----------------------------------|
%                  |  Predicted optimal temperatures  |
%                  |----------------------------------|
%
% CSV file with two columns, which contains predicted optimal temperatures
% for all proteins in the ecAraCore model. This file can be regenerated by
% using the trained Random Forest regressor provided at
% https://github.com/pwendering/tpppredict .
topt_prediction_file = fullfile(pathToTGEM, 'protein-stability',....
    'topt-prediction', 'topt_predicted.csv');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                  |-------------------|
%                  |  Protein content  |
%                  |-------------------|
%
% TAB-separated file that contains measurements of total protein content
% across multiple temperatures. The file procided here comprises data from
% multiple studies for A. thaliana Col-0.
% The first row contains the column headers, which are the temperatures in °C.
%
% If the values in the provided file are given per gram fresh weight (FW),
% a conversion factor to dry weight (DW) must be provided.
% Remove the variable DW2FW or set it to NaN if the protein content data
% are given per gFW.
% Please not that the unit must be either mg/gFW or mg/gDW.
proteinContentFile = fullfile(pathToTGEM, 'protein-content', 'ath-protein-content.tsv');
% Pyl et al. 2012 average over all conditions for Col-0 (ED), SI Table 2
DW2FW = 0.094;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                  |----------------------|
%                  |  Leaf mass per area  |
%                  |----------------------|
%
% TAB-separated file that contains measurements of the leaf mass per area
% [gDW m^-2] across multiple temperatures. The file procided here comprises
% data from multiple studies for A. thaliana Col-0.
% The first row contains the column headers, which are the temperatures in °C.
lmaFile = fullfile(pathToTGEM, 'photosynthesis-parameters', 'ath-lma.tsv');

%% Experimental conditions
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                      |-------------------|
%                      |  Temperature [K]  |
%                      |-------------------|
% A standard value of 25 °C (298.15 K) is set.
T = 294.15;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                |------------------------------------|
%                |  Irradiance/PPFD [umol m^-2 s^-1]  |
%                |------------------------------------|
I = 100;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                        |-----------------|
%                        |  p(CO2) [ubar]  |
%                        |-----------------|
%
% This parameter sets the value for the ambient partial pressue of CO2.
C_a = 400;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                        |-----------------|
%                        |   p(O2) [ubar]  |
%                        |-----------------|
%
% This parameter sets the value for the ambient partial pressue of O2. Air
% contains 21% oxygen, which corresponds to a partial pressure of 210 mbar.
O_a = 210000;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                           |----------|
%                           |  RH [%]  |
%                           |----------|
%
% This parameter sets the value for the relative humidity.
RH = 60;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                    |------------------------------|
%                    |  Atmospharic pressure [bar]  |
%                    |------------------------------|
%
% This parameter sets the value for the atmospheric pressure. The standard
% value is 1.01325 bar or 1 atm.
P = 1.01325;
%% Parameters for Farquhar photosynthesis model (Farquhar et al. 1980)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%            |----------------------------------------------|
%            |  Turnover number of RuP2 carboxylase [s^-1]  |
%            |----------------------------------------------|
%
% A value of 4.4 s^-1 is set as default, which is an in vivo measurement,
% obtained from Walker et al. (2013), DOI: 10.1111/pce.12166 (A. thaliana Col-0).
k_c = 4.4;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%            |--------------------------------------------|
%            |  Turnover number of RuP2 oxygenase [s^-1]  |
%            |--------------------------------------------|
%
% The value is obtained by multiplying the kcat for the carboxylation
% reaction is the ratio between the maximum velocities of carboxylation and
% oxygenation at 25 °C (V_o_max/V_c_max = 0.29). This ratio was obtained
% from Walker et al. (2013), DOI: 10.1111/pce.12166 (A. thaliana Col-0).
k_o = k_c * 0.29;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%         |-------------------------------------------------------|
%         |  Michaelis-Menten constant of RuBisCO for CO2 [ubar]  |
%         |-------------------------------------------------------|
%
% A value of 265 ubar was set as default, which was obtained from
% Walker et al. (2013), DOI: 10.1111/pce.12166 (A. thaliana Col-0).
K_c = 265;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%         |------------------------------------------------------|
%         |  Michaelis-Menten constant of RuBisCO for O2 [ubar]  |
%         |------------------------------------------------------|
%
% A value of 201000 ubar was set as default, which was obtained from
% Walker et al. (2013), DOI: 10.1111/pce.12166 (A. thaliana Col-0).
K_o = 201000;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%         |-----------------------------------------------------|
%         |  Relative specificity of RuBisCO for carboxylation  |
%         |  over oxygenation [bar bar^-1]                      |
%         |-----------------------------------------------------|
%
% A value of 2615 bar bar^-1 was set as default, which was obtained from
% Walker et al. (2013), DOI: 10.1111/pce.12166 (A. thaliana Col-0). The relative
% specificy can also be expressed in terms of concentrations instead of partial
% pressures. To convert one into the other, the ratio of Henry constants
% for CO2 and O2 serves as a conversion factor:
%          S_co(bar/bar) = S_co(mol/mol) * (0.031/0.0013) .
% For the calculation of phi for constraint-based modelling, S_co is
% calculated by
%              S_co = ( k_c / K_c ) * ( K_o / k_o ) .
S_co = 2615;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%        |---------------------------------------------------------|
%        |  Ratio between chloroplastic O2 and CO2 concentrations  |
%        |---------------------------------------------------------|
%
% At the time of generating this model, we were not aware of a reliable way
% to estimate or model the O2 concentration in the chloroplast. However, it
% is expected that the ratio will be different from the ratio of ambient O2
% and CO2. Therefore, we introduced a parameter gamma, which allows setting
% the ratio of chloroplastic O2 and CO2 to a specified value. For instance
% in the FvCB model, the ambient O2 and intercellular CO2 partial pressures 
% were used to calulate the ratio between oxygenation and carboxylation,
% phi. In this case, gamma would equal to 1.33 * O_a / C_a, assuming a
% ratio of 0.75 between Ci and Ca.
gamma = O_a / C_a;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%          |---------------------------------------------------|
%          |  Maximum carboxylation velocity [umol m^-2 s^-1]  |
%          |---------------------------------------------------|
%
% The default value of 96.30 umol m^-2 s^-1 originates from
% Heckwolf et al. (2011), DOI:  10.1007/s11120-011-9651-3 (maximum value
% for A. thaliana Col-0 at 25 °C).
V_c_max = 96.30;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                |--------------------------|
%                |  J_max [umol m^-2 s^-1]  |
%                |--------------------------|
%
% This parameter describes the light-saturated potential rate of electron
% transport. The given default value was taken from Gandin et al. (2012),
% DOI: 10.1093/pcp/pcs107 (A. thaliana Col-0, 25 °C, p(O2)=184 mbar).
J_max = 138.5;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%               |--------------------------------------------|
%               |  Boundary layer resistance [m^2 s mol^-1]  |
%               |--------------------------------------------|
%
% This parameter sets the value for the boundary layer resistance to water
% vapour. The leaf boundary layer is the region between the leaf surface
% and ambient air, where air flow is more turbulant than the laminar air
% flow in the boundary layer. It is influenced by e.g. wind speed, leaf
% anatomy and shape, or canopy density. A thick boundary layer can decrease
% water loss, but also hamper gas exchange. A value of 1 m^2 s mol^-1 is
% set here as in Farquhar and Wong (1984), DOI: 10.1071/pp9840191.
r_b = 1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                |----------------------------------------|
%                |  Stomatal conductance [mol m^-2 s^-1]  |
%                |----------------------------------------|
%
% This parameter describes the conductivity of the stomata to CO2. The
% given default value is a rounded average over multiple studies for
% A. thaliana Col-0 at 25 °C. The function that adjusts the stomatal
% conductance to difference temperatures does not use this standard value.
% Instead, a second-degree polynomial function is fitted to data from von
% Caemmerer and Evans (2015) (A. thaliana Col-0) to obtain an empirical
% temperature model. The name of the adjustment function is "adj_g_s".
g_s = 0.2;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%           |------------------------------------------------|
%           |  Mesophyll conductance [mol bar^-1 m^-2 s^-1]  |
%           |------------------------------------------------|
%
% This parameter describes the conductivity of the mesophyll to CO2. The
% given default value is a rounded average over multiple studies for
% A. thaliana Col-0 at 25 °C. For the constraint-based modelling, different
% methods can be used to adjust the mesophyll conductance to different
% temperatures. Not all of them use this standard value. The name of the
% adjustment function is "adj_g_m".
g_m = 0.2;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%             |--------------------------------------------|
%             |  Method for temperature adjustment of g_m  |
%             |--------------------------------------------|
%
% Specifies the method / model that should be used to adjust the mesophyll
% conductance to different temperatures ("adj_g_m.m"). Four different
% temperature models can be used:
% 'walker' (default)    Walker et al. (2013), DOI: 10.1111/pce.12166
% 'caemmerer'           von Caemmerer and Evans (2015), DOI: 10.1111/pce.12449
% 'niinemets'           Niinemets et al. (2009), DOI: 10.1093/jxb/erp063
% 'empirical'           Gaussian fit to data from
%                       von Caemmerer and Evans (2015), DOI: 10.1111/pce.12449
% For more info, please refer to "adj_g_m.m" or the original literature.
g_m_method = 'walker';
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%         |----------------------------------------------------|
%         |  Number of released CO2 molecules per oxygenation  |
%         |----------------------------------------------------|
%
% This parameter allows to set the number of molecules CO2 released per
% oxygenation (photorespiration).
alpha = 0.5;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%             |--------------------------------------------|
%             |  Absorptance / quantum yield of red light  |
%             |--------------------------------------------|
%
% This parameter affects the irradiance that can be used by the leaf.
absorptance = 0.85;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%        |-------------------------------------------------------|
%        |  Correction factor for the spectral quality of light  |
%        |-------------------------------------------------------|
%
% This parameter affects the irradiance that can be used by the leaf.
sqcf = 0.15;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%           |---------------------------------------------|
%           |  Convexity factor for the light dependence  |
%           |  of the electron transport rate             |
%           |---------------------------------------------|
%
% This parameter affects the relationship of the apparent electron
% transport rate with the apparent irradiance.
theta = 0.7;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%       |----------------------------------------------------------|
%       |  Day respiration or "Dark respiration" [umol m^-2 s^-1]  |
%       |----------------------------------------------------------|
%
% This parameter sets the rate of CO2 release excluding photorespiration.
% The default value of 0.86 umol m^-2 s^-1 originates from the original FvCB
% model (Farquhar et al. (1980), DOI: 10.1007/BF00386231).
R_d = 0.86;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                 |---------------------------------|
%                 |  Ratio between oxygenation and  |
%                 |  carboxylation reactions        |
%                 |---------------------------------|
%
% The default value of 0.27 originates from the original FvCB model
% (Farquhar et al. (1980), DOI: 10.1007/BF00386231). For the constraints
% based on the FvCB model, phi is determined by
%                 phi = p(O2) / ( S_co * p(CO2) ).
phi = 0.27;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%          |------------------------------------------------|
%          |  Triose phosphate utilization [mol m^-2 s^-1]  |
%          |------------------------------------------------|
%
% The default value of 8.14 mol m^-2 s^-1 originates from
% Morales et al. (2018), DOI: 10.1111/pce.13119 (A. thaliana).
TPU = 8.14;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                |--------------------------------------|
%                |  Activation energies for FvCB model  |
%                |  parameters [J mol^-1]               |
%                |--------------------------------------|
%
% Activation energies for temperature adjustment of RuBisCO kcat values and
% Michaelis-Menten constants for the carboxylation and oxygenation
% reactions are obtained from Farquhar et al. (1980), DOI:
% 10.1007/BF00386231.
% The actual activation / deactivation energies or other constants that are
% used in the temperature adjustment functions may differ as these
% parameters given here are primarily used as input for the original FvCB
% model.
E_a = struct;
E_a.K_c     = 59356;
E_a.K_o     = 35948;
E_a.k_c     = 58520;
E_a.k_o     = 58520;
E_a.V_c_max = 58520;

%% Constraint-based modelling parameters
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                |-------------------------------------------|
%                |  Allowed deviation of phi ( V_o / V_c) )  |
%                |-------------------------------------------|
%
% This parameter is used to define the lower and upper bounds for the ratio
% between the oxygenation and carboxylation reaction:
%       (1-tau) * phi <= v_o/v_c <= (1+tau) * phi
tau = 0.001;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                |----------------------------------|
%                |  Unit conversion scaling factor  |
%                |----------------------------------|
%
% The units of the FvCB model parameters are converted to units of the
% metabolic model:
%   umol -> mmol
%   m^2  -> gDW (gram dry weight)
%   s    -> h
% Even though the units match, the fluxes and the resulting net CO2
% assimmilation rate (A_net) do not necessarily match. If the fluxes in the
% model are too low to guarantee a resonably high A_net, a scaling factor
% for the unit conversion can be used. This factor is multiplied with the
% converted FvCB model parameters. When A_net is obtained from the solution
% of the optimization problem, the same scaling factor is used to convert
% the units back to umol m^-2 s^-1.
fvcb_scaling = 10;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                |----------------------------------|
%                |  Turnover number scaling factor  |
%                |----------------------------------|
%
% When using in vitro kcat values from BRENDA as contained in ecModels
% generated using GECKO, the predicted growth rate can be lower than
% expacted considering experimental measurements. The specified scaling
% factor is a very general way to address this problem without relying on
% the kcat correction procedure of GECKO, which did not finish in
% reasonable time. Using PRESTO (Wendering & Arend et al. (2023), DOI: 
% 10.1038/s41467-023-37151-2) is an option that remains to be fully
% explored as multiple proteomics datasets are available.
% Therefore, all kcat values in the ecModel are multiplied with a scaling
% factor.
kcat_scaling = 20;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                  |----------------------------|
%                  |  Gurobi solver parameters  |
%                  |----------------------------|
%
% Parameters for the Gurobi solver for solving the
% quadratically-constrained optimization problem with FvCB model
% constraints.
solver_params = struct;
solver_params.NonConvex      = 2;
solver_params.OutputFlag     = 0;
solver_params.NumericFocus   = 3;
solver_params.MIPFocus       = 3;
solver_params.FeasibilityTol = 1e-9;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%       |----------------------------------------------------|
%       |  Reaction identifies in the metabolic model        |
%       |  that are relevant for the FvCB model constraints  |
%       |----------------------------------------------------|
%
% Reaction ID of the RuBisCO carboxylation reaction
C_ID       = 'arm_RBC_h';
% Reaction ID of the RuBisCO oxygenation reaction
O_ID       = 'arm_RBO_h';
% Reaction ID of the transport reaction that exports CO2 from the
% mitochondrion compartment to the cytosol compartment
RESP_ID    = 'Tr_CO2m_REV';
% Reaction ID of the exchange reaction for CO2
% * -> CO2
CO2_IMP_ID = 'Im_CO2';
% Reaction ID of the photon import reaction
% * -> photons
ABS_ID     = 'Im_hnu';
% Reaction ID of the biomass reaction
BIO_ID     = 'Bio_opt';
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Constants
% universal gas constant [J K^-1 mol^-1]
R = 8.31446261815324;
% Boltzmann constant [J K^-1]
kB = 1.380649E-23;
% Planck constant [J s]
h = 6.62607015E-34;

%% Set solver for COBRA toolbox
if ~paramFlag
    try
        changeCobraSolver('gurobi','all',0);
    catch
        % use default solver
        initCobraToolbox(false)
    end
end
if paramFlag
    if ~exist(parameter_name, 'var')
        fprintf('Parameter %s does not exist.\n', parameter_name)
        parameter_value = {};
    else
        parameter_value = eval(parameter_name);
    end
end
end
