function evaluatePredictionsMultiRenzo
% Compare model predictions to experimental data

top_dir = regexprep(mfilename('fullpath'), '(\\[^\\]+){2}$', '');
data_dir = fullfile(top_dir, 'data');
result_dir = fullfile(top_dir, 'results');

%% Load experimental data

% mean reporter intensities
load(fullfile(result_dir, 'measured_protein_abundances'), ...
    'mean_intensities', ...
    'protein_IDs', ...
    'sd_intensities')
n_cond = size(mean_intensities, 2);
n_prot = numel(protein_IDs);

mean_intensities_scaled = mean_intensities./max(mean_intensities);
sd_intensities_scaled = sd_intensities./max(mean_intensities);

%% Load predictions
date_str = '20251031';
load(fullfile(result_dir, ['renzo_workspace_walker_' date_str '.mat']), ...
    'samples', 'min_abundances', 'max_abundances', 'renzo_sol', ...
    'renzo_problem', 'model', 'O2', 'T')

model.subSystems(cellfun(@isempty, model.subSystems)) = {''};

prot_idx = find(startsWith(renzo_problem.varnames, 'draw_prot_'));
prot_samples = cell2mat(cellfun(@(x)full(x(prot_idx, :)), samples, 'un', 0));

n_samples = size(prot_samples, 2);

%% Calculate overall average coverage per condition across all samples

total_coverages = arrayfun(@(i) ...
    getSamplingCoverage(prot_samples((i-1)*n_prot+1:i*n_prot, :), ...
    min_abundances(:, i), max_abundances(:, i)), 1:n_cond);

%% Check for agreement with experimental observations

nz_idx = all(mean_intensities>0, 2);

% Single prediction
prot_abundances_pred_single = reshape(renzo_sol.x(prot_idx), [], n_cond);
prot_abundances_pred_single(prot_abundances_pred_single<1e-9) = 0;
prot_abundances_pred_single_scaled = prot_abundances_pred_single./max(prot_abundances_pred_single);
prot_abundances_pred_single_scaled_nz = prot_abundances_pred_single_scaled(nz_idx, :);

mean_intensities_scaled_nz = mean_intensities_scaled(nz_idx, :);

% Correlation to scaled measurements
corr_mat = corr( ...
    prot_abundances_pred_single_scaled_nz, ...
    mean_intensities_scaled_nz, ...
    'type', 'Spearman');

disp('Correlations from single prediction')
disp(diag(corr_mat)')

xylim = [ ...
    min( ...
    [prot_abundances_pred_single_scaled_nz(all(prot_abundances_pred_single_scaled_nz>0, 2), :); ...
    mean_intensities_scaled_nz], [], 'all'), ...
    max([prot_abundances_pred_single_scaled_nz; mean_intensities_scaled_nz], [], 'all') ...
    ];

figure
t = tiledlayout(1, 3);
letters = 'ABC';
for i = 1:size(prot_abundances_pred_single, 2)
    
    nexttile
    plot([1e-8 1], [1e-8 1], 'k')
    hold on
    scatter(...
        mean_intensities_scaled_nz(:, i), ...
        prot_abundances_pred_single_scaled_nz(:, i), ...
        'filled')
    
    text(0.5, 0.9, sprintf('r_S = %.2f', corr_mat(i, i)), ...
        'Units', 'normalized', 'HorizontalAlignment', 'center')
    text(0.1, 0.9, letters(i), ...
        'Units', 'normalized', 'HorizontalAlignment', 'center', ...
        'FontWeight', 'bold', 'FontSize', 12)
    
    set(gca, ...
        'YScale', 'log', ...
        'XScale', 'log', ...
        'XLim', xylim, ...
        'YLim', xylim, ...
        'FontSize', 12)
    
end

t.XLabel.String = {'scaled reporter intensity', '(measured)'};
t.XLabel.FontSize = 14;

t.YLabel.String = {'scaled abundances', '(predicted)'};
t.YLabel.FontSize = 14;

set(gcf, 'OuterPosition', [321.8000  456.2000  876.0000  364.4000])

exportgraphics(gcf, ...
    fullfile(result_dir, 'scatter_pred_meas_single_prediction.png'), ...
    'Resolution', 300)

% Correlation across samples
sample_correlations = zeros(n_samples, n_cond);

for i = 1:n_samples
    
    tmp_prot_abundances = reshape(prot_samples(:, i), [], n_cond);
    tmp_prot_abundances(tmp_prot_abundances<1e-9) = 0;
    corr_mat = corr( ...
        tmp_prot_abundances(nz_idx, :)./max(tmp_prot_abundances(nz_idx, :)), ...
        mean_intensities(nz_idx, :)./max(mean_intensities(nz_idx, :)), ...
        'type', 'Spearman');
    sample_correlations(i, :) = diag(corr_mat);

end

disp('Average correlations from sampling')
disp(mean(sample_correlations))
disp('Maximum correlations from sampling')
disp(max(sample_correlations))

% Find sample with higest average correlation across the three conditions
[~, idx_best_sample] = max(mean(sample_correlations, 2));
best_correlations = sample_correlations(idx_best_sample, :);

best_sample_abundances = reshape(prot_samples(:, idx_best_sample(1)), [], n_cond);
best_sample_abundances(best_sample_abundances<1e-9) = 0;
best_sample_abundances_scaled = best_sample_abundances./max(best_sample_abundances);
best_sample_abundances_scaled_nz = best_sample_abundances_scaled(nz_idx, :);

xylim = [ ...
    min( ...
    [best_sample_abundances_scaled_nz(all(best_sample_abundances_scaled_nz>0, 2), :); ...
    mean_intensities_scaled_nz], [], 'all'), ...
    max([best_sample_abundances_scaled_nz; mean_intensities_scaled_nz], [], 'all') ...
    ];

figure
t = tiledlayout(1, 3);
for i = 1:n_cond
    
    nexttile
    plot([1e-8 1], [1e-8 1], 'k')
    hold on
    scatter(...
        mean_intensities_scaled_nz(:, i), ...
        best_sample_abundances_scaled_nz(:, i), ...
        'filled')
    
    text(0.5, 0.9, sprintf('r_S = %.2f', best_correlations(i)), ...
        'Units', 'normalized', 'HorizontalAlignment', 'center')
    text(0.1, 0.9, letters(i), ...
        'Units', 'normalized', 'HorizontalAlignment', 'center', ...
        'FontWeight', 'bold', 'FontSize', 12)
    
    set(gca, ...
        'YScale', 'log', ...
        'XScale', 'log', ...
        'XLim', xylim, ...
        'YLim', xylim, ...
        'FontSize', 12)
    
end

t.XLabel.String = {'scaled reporter intensity', '(measured)'};
t.XLabel.FontSize = 14;

t.YLabel.String = {'scaled abundances', '(predicted)'};
t.YLabel.FontSize = 14;

set(gcf, 'OuterPosition', [321.8000  456.2000  876.0000  364.4000])

exportgraphics(gcf, ...
    fullfile(result_dir, 'scatter_pred_meas_best_sample.png'), ...
    'Resolution', 300)

%% Check overlap of proteins

% UniProt IDs of proteins per metabolic subsystem
uniprot_files = fullfile(data_dir, {
    'carb_met_uniprot.txt', ...
    'lipids_uniprot.txt', ...
    'light_rxns_uniprot.txt', ...
    'ros_genes_uniprot.txt', ...
    'photorespiration_uniprot.txt' ...
    });

model_proteins = erase(model.rxns(startsWith(model.rxns, 'draw_prot_')), 'draw_prot_');

prot_subsystems_model = cell(numel(uniprot_files), 1);

prot_correlations_single = zeros(numel(uniprot_files), n_cond);
prot_correlations_best_sample = zeros(numel(uniprot_files), n_cond);
prot_correlations_sampling_av = zeros(numel(uniprot_files), n_cond);

for i = 1:numel(uniprot_files)
    
    subsystem = erase(uniprot_files{i}, '_uniprot.txt');
    
    % Read text file
    tmp_prots = table2cell(readtable(uniprot_files{i}, ...
        'ReadVariableNames', false));
    
    % Find overlapping proteins
    prots_in_model = ismember(model_proteins, tmp_prots);
    
    fprintf('%i proteins (%2.2f%%) in %s are contained in the model.\n', ...
        sum(prots_in_model), 100*sum(prots_in_model)/numel(tmp_prots), ...
        subsystem)
    
    % Only consider proteins with measurements
    prots_in_model = prots_in_model & nz_idx;
    
    fprintf('%i proteins (%2.2f%%) in %s are contained in the model and are expressed.\n', ...
        sum(prots_in_model), 100*sum(prots_in_model)/numel(tmp_prots), ...
        subsystem)
    
    % Subsystems of overlapping proteins in the model
    overlap_rxns = findRxnsFromMets(model, ...
        strcat('prot_', model_proteins(prots_in_model)));
    overlap_subsyst = model.subSystems(ismember(model.rxns, overlap_rxns));
    overlap_subsyst_all = cellfun(@(x)strsplit(x, ', '), overlap_subsyst, 'un', 0);
    overlap_subsyst_uniq = unique([overlap_subsyst_all{:}]);
    prot_subsystems_model{i} = overlap_subsyst_uniq;
    
    % Calculate Spearman correlations
    if sum(prots_in_model)>0
        
        prot_correlations_single(i, :) = diag(corr( ...
            prot_abundances_pred_single_scaled(prots_in_model, :), ...
            mean_intensities_scaled(prots_in_model, :), ...
            'rows', 'complete', ...
            'type', 'Spearman'));
        
        prot_correlations_best_sample(i, :) = diag(corr( ...
            best_sample_abundances_scaled(prots_in_model, :), ...
            mean_intensities_scaled(prots_in_model, :), ...
            'rows', 'complete', ...
            'type', 'Spearman'));
        
        tmp_corr = zeros(n_cond, n_samples);
        for j = 1:n_samples
            
            tmp_prot_abundances = reshape(prot_samples(:, j), [], n_cond);
            tmp_prot_abundances(tmp_prot_abundances<1e-9) = 0;
            corr_mat = corr( ...
                tmp_prot_abundances(prots_in_model, :)./max(tmp_prot_abundances(nz_idx, :)), ...
                mean_intensities(prots_in_model, :)./max(mean_intensities(nz_idx, :)), ...
                'type', 'Spearman');
            tmp_corr(:, j) = diag(corr_mat);
            
        end
        prot_correlations_sampling_av(i, :) = mean(tmp_corr, 2, 'omitnan');
        
    end
end

%% Write results

% Correlations with specific subsets
f_name = fullfile(result_dir, ['correlation_analysis_' date_str '.xlsx']);
writetable( ...
    array2table(prot_correlations_single, ...
    'VariableNames', arrayfun(@(i)sprintf('%i mbar', i), O2/1000, 'un', 0), ...
    'RowNames', erase(uniprot_files, '_uniprot.txt')), ...
    f_name, ...
    'WriteRowNames', true, ...
    'Range', 'A2', ...
    'Sheet', 'correlation_single_prediction')

writetable( ...
    array2table(prot_correlations_sampling_av, ...
    'VariableNames', arrayfun(@(i)sprintf('%i mbar', i), O2/1000, 'un', 0), ...
    'RowNames', erase(uniprot_files, '_uniprot.txt')), ...
    f_name, ...
    'WriteRowNames', true, ...
    'Range', 'A2', ...
    'Sheet', 'correlation_average_samples')

writetable( ...
    array2table(prot_correlations_best_sample, ...
    'VariableNames', arrayfun(@(i)sprintf('%i mbar', i), O2/1000, 'un', 0), ...
    'RowNames', erase(uniprot_files, '_uniprot.txt')), ...
    f_name, ...
    'WriteRowNames', true, ...
    'Range', 'A2', ...
    'Sheet', 'correlation_best_sample')

writetable( ...
    array2table(prot_abundances_pred_single, ...
    'VariableNames', arrayfun(@(i)sprintf('%i_mbar', i), O2/1000, 'un', 0), ...
    'RowNames', protein_IDs), ...
    f_name, ...
    'WriteRowNames', true, ...
    'Range', 'A2', ...
    'Sheet', 'abundances_single_prediction')

writetable( ...
    array2table(best_sample_abundances, ...
    'VariableNames', arrayfun(@(i)sprintf('%i mbar.csv', i), O2/1000, 'un', 0), ...
    'RowNames', protein_IDs), ...
    f_name, ...
    'WriteRowNames', true, ...
    'Range', 'A2', ...
    'Sheet', 'abundances_best_sample')

writetable( ...
    array2table(mean_intensities, ...
    'VariableNames', arrayfun(@(i)sprintf('%i mbar', i), O2/1000, 'un', 0), ...
    'RowNames', protein_IDs), ...
    f_name, ...
    'WriteRowNames', true, ...
    'Range', 'A2', ...
    'Sheet', 'mean_intensities_measured')

%% Test specific hypotheses

% 1) Starch and sucrose synthesis serve as electron sink under low O2
% conditions, replacing the electron sink capacity of photorespiration
% compared to the normal O2 condition

% => Is there an increased flux and protein abundances in starch and
% sucrose synthesis pathways?

% === starch synthesis

% fluxes
starch_synthesis_rxns = findRxnsFromSubSystem(model, 'starch synthesis');
flux_starch_synthesis = cell2mat(arrayfun(@(i) ...
    samples{i}(ismember(renzo_problem.varnames, starch_synthesis_rxns), :), ...
    1:n_cond, 'un', 0));
flux_starch_synthesis = cell2mat(arrayfun(@(i) ...
    sum(full(flux_starch_synthesis((i-1)*numel(starch_synthesis_rxns)+1:i*numel(starch_synthesis_rxns), :))), ...
    1:n_cond, 'un', 0)');

% protein abundances
starch_synthesis_mets = findMetsFromRxns(model, starch_synthesis_rxns);
starch_synthesis_proteins = strcat('draw_', starch_synthesis_mets(startsWith(starch_synthesis_mets, 'prot_')));

abundances_starch_synthesis = cell2mat(arrayfun(@(i) ...
    samples{i}(ismember(renzo_problem.varnames, starch_synthesis_proteins), :), ...
    1:n_cond, 'un', 0));
abundances_starch_synthesis = cell2mat(arrayfun(@(i) ...
    sum(full(abundances_starch_synthesis((i-1)*numel(starch_synthesis_proteins)+1:i*numel(starch_synthesis_proteins), :))), ...
    1:n_cond, 'un', 0)');

% === sucrose synthesis

% fluxes
sucrose_synthesis_rxns = findRxnsFromSubSystem(model, 'sucrose synthesis');
flux_sucrose_synthesis = cell2mat(arrayfun(@(i) ...
    samples{i}(ismember(renzo_problem.varnames, sucrose_synthesis_rxns), :), ...
    1:n_cond, 'un', 0));
flux_sucrose_synthesis = cell2mat(arrayfun(@(i) ...
    sum(full(flux_sucrose_synthesis((i-1)*numel(sucrose_synthesis_rxns)+1:i*numel(sucrose_synthesis_rxns), :))), ...
    1:n_cond, 'un', 0)');

% protein abundances
% !! majority at abundances < 1e-9 (feasibility tolerance)
sucrose_synthesis_mets = findMetsFromRxns(model, sucrose_synthesis_rxns);
sucrose_synthesis_proteins = strcat('draw_', sucrose_synthesis_mets(startsWith(sucrose_synthesis_mets, 'prot_')));

abundances_sucrose_synthesis = cell2mat(arrayfun(@(i) ...
    samples{i}(ismember(renzo_problem.varnames, sucrose_synthesis_proteins), :), ...
    1:n_cond, 'un', 0));
abundances_sucrose_synthesis = cell2mat(arrayfun(@(i) ...
    sum(full(abundances_sucrose_synthesis((i-1)*numel(sucrose_synthesis_proteins)+1:i*numel(sucrose_synthesis_proteins), :))), ...
    1:n_cond, 'un', 0)');

% => Does the flux and protein abundances in photorespiration change?

% fluxes
photorespiration_rxns = findRxnsFromSubSystem(model, 'photorespiration');
flux_photorespiration = cell2mat(arrayfun(@(i) ...
    samples{i}(ismember(renzo_problem.varnames, photorespiration_rxns), :), ...
    1:n_cond, 'un', 0));
flux_photorespiration = cell2mat(arrayfun(@(i) ...
    sum(full(flux_photorespiration((i-1)*numel(photorespiration_rxns)+1:i*numel(photorespiration_rxns), :))), ...
    1:n_cond, 'un', 0)');

% protein abundances
photorespiration_mets = findMetsFromRxns(model, photorespiration_rxns);
photorespiration_proteins = strcat('draw_', photorespiration_mets(startsWith(photorespiration_mets, 'prot_')));

abundances_photorespiration = cell2mat(arrayfun(@(i) ...
    samples{i}(ismember(renzo_problem.varnames, photorespiration_proteins), :), ...
    1:n_cond, 'un', 0));
abundances_photorespiration = cell2mat(arrayfun(@(i) ...
    sum(full(abundances_photorespiration((i-1)*numel(photorespiration_proteins)+1:i*numel(photorespiration_proteins), :))), ...
    1:n_cond, 'un', 0)');

% ========================================================================
% 2) Phosphoglycolate phosphatase, glycolate oxidase, and catalase acclimate to
% photorespiratory pressure, but downstream photorespiratory enzymes do
% not.

adj_pr_enzymes = strcat('draw_prot_', {'P0DKC3', 'Q9LRR9', 'Q42547'});
remain_pr_enzymes = photorespiration_proteins(~ismember(photorespiration_proteins, adj_pr_enzymes));

abundances_adj_pr_enyzmes = cell2mat(arrayfun(@(i) ...
    samples{i}(ismember(renzo_problem.varnames, adj_pr_enzymes), :), ...
    1:n_cond, 'un', 0));
abundances_adj_pr_enyzmes = cell2mat(arrayfun(@(i) ...
    sum(full(abundances_adj_pr_enyzmes((i-1)*numel(adj_pr_enzymes)+1:i*numel(adj_pr_enzymes), :))), ...
    1:n_cond, 'un', 0)');

abundances_remain_pr_enyzmes = cell2mat(arrayfun(@(i) ...
    samples{i}(ismember(renzo_problem.varnames, remain_pr_enzymes), :), ...
    1:n_cond, 'un', 0));
abundances_remain_pr_enyzmes = cell2mat(arrayfun(@(i) ...
    sum(full(abundances_remain_pr_enyzmes((i-1)*numel(remain_pr_enzymes)+1:i*numel(remain_pr_enzymes), :))), ...
    1:n_cond, 'un', 0)');

% ========================================================================
% 3) Alternative oxidases help dissipate excess electron transport under
% higher photorespiratory rates to compensate for increased ATP/NADPH
% demand.

% AOX expression
aox_proteins = strcat('draw_prot_', ...
    {'O22049', 'Q39219', 'O23913', 'O22048', 'Q8LEE7', 'Q56X52'});

abundances_aox = cell2mat(arrayfun(@(i) ...
    samples{i}(ismember(renzo_problem.varnames, aox_proteins), :), ...
    1:n_cond, 'un', 0));
abundances_aox = cell2mat(arrayfun(@(i) ...
    sum(full(abundances_aox((i-1)*numel(aox_proteins)+1:i*numel(aox_proteins), :))), ...
    1:n_cond, 'un', 0)');

aox_rxns = findRxnsFromMets(model, erase(aox_proteins, 'draw_'));
aox_rxns = aox_rxns(~startsWith(aox_rxns, 'draw_prot'));
flux_aox = cell2mat(arrayfun(@(i) ...
    samples{i}(ismember(renzo_problem.varnames, aox_rxns), :), ...
    1:n_cond, 'un', 0));
flux_aox = cell2mat(arrayfun(@(i) ...
    sum(full(flux_aox((i-1)*numel(aox_rxns)+1:i*numel(aox_rxns), :))), ...
    1:n_cond, 'un', 0)');

% ========================================================================
% 4) Lipid-related proteins are more abundant under 2% and 40% oxygen.
%  ==> not enough lipid-related proteins/reactions in the model

% ========================================================================
% 5) Light reaction-related proteins are less abundant at 2% and 40% O2,
% compared to 21% O2.

% fluxes
light_reactions_rxns = findRxnsFromSubSystem(model, 'light reactions');
flux_light_reactions = cell2mat(arrayfun(@(i) ...
    samples{i}(ismember(renzo_problem.varnames, light_reactions_rxns), :), ...
    1:n_cond, 'un', 0));
flux_light_reactions = cell2mat(arrayfun(@(i) ...
    sum(full(flux_light_reactions((i-1)*numel(light_reactions_rxns)+1:i*numel(light_reactions_rxns), :))), ...
    1:n_cond, 'un', 0)');

% protein abundances
light_reactions_mets = findMetsFromRxns(model, light_reactions_rxns);
light_reactions_proteins = strcat('draw_', light_reactions_mets(startsWith(light_reactions_mets, 'prot_')));

abundances_light_reactions = cell2mat(arrayfun(@(i) ...
    samples{i}(ismember(renzo_problem.varnames, light_reactions_proteins), :), ...
    1:n_cond, 'un', 0));
abundances_light_reactions = cell2mat(arrayfun(@(i) ...
    sum(full(abundances_light_reactions((i-1)*numel(light_reactions_proteins)+1:i*numel(light_reactions_proteins), :))), ...
    1:n_cond, 'un', 0)');

% ========================================================================
% 6) The 49 core hypoxia proteins regulated by ERF-VII signaling require
% adjustment at 2% O2, but not under 40% O2, compared to 21% O2.

core_hypoxia_protein_tab = readtable( ...
    fullfile(data_dir, 'hypoxia_response_up.tsv'), ...
    'FileType', 'text');

core_hypoxia_proteins = model.mets(ismember(model.mets, ...
    strcat('prot_', core_hypoxia_protein_tab.Entry)));
core_hypoxia_rxns = findRxnsFromMets(model, core_hypoxia_proteins);
core_hypoxia_rxns = core_hypoxia_rxns(~startsWith(core_hypoxia_rxns, 'draw_prot'));
core_hypoxia_proteins = strcat('draw_', core_hypoxia_proteins);

% proteins found in the model:
% Q9LXL5: Sucrose synthase 4
% Q9M076: ATP-dependent 6-phosphofructokinase 6
% F4I7I0: Alanine aminotransferase 1, mitochondrial

abundances_core_hypoxia_proteins = cell2mat(arrayfun(@(i) ...
    samples{i}(ismember(renzo_problem.varnames, core_hypoxia_proteins), :), ...
    1:n_cond, 'un', 0));
abundances_core_hypoxia_proteins = cell2mat(arrayfun(@(i) ...
    sum(full(abundances_core_hypoxia_proteins((i-1)*numel(core_hypoxia_proteins)+1:i*numel(core_hypoxia_proteins), :))), ...
    1:n_cond, 'un', 0)');

flux_core_hypoxia_rxns = cell2mat(arrayfun(@(i) ...
    samples{i}(ismember(renzo_problem.varnames, core_hypoxia_rxns), :), ...
    1:n_cond, 'un', 0));
flux_core_hypoxia_rxns = cell2mat(arrayfun(@(i) ...
    sum(full(flux_core_hypoxia_rxns((i-1)*numel(core_hypoxia_rxns)+1:i*numel(core_hypoxia_rxns), :))), ...
    1:n_cond, 'un', 0)');

% ========================================================================
% 7) Electron transport rate

% Compare calculated rates from the experiments with flux though PSII
% reaction in the model.

electron_transport_exp_tab = readtable( ...
    fullfile(data_dir, 'electron_transport_rates_7h.csv'));
electron_transport_exp_mean = arrayfun(@(i) ...
    mean(electron_transport_exp_tab.electron_transport_rate((i-1)*4+1:i*4)), ...
    1:numel(O2));
electron_transport_exp_mean = electron_transport_exp_mean([3, 1, 2]);

electron_transport_exp_sd = arrayfun(@(i) ...
    std(electron_transport_exp_tab.electron_transport_rate((i-1)*4+1:i*4)), ...
    1:numel(O2));
electron_transport_exp_sd = electron_transport_exp_sd([3, 1, 2]);

psII_rxns = model.rxns(startsWith(model.rxns, 'PSII_'));
flux_psII = cell2mat(arrayfun(@(i) ...
    samples{i}(ismember(renzo_problem.varnames, psII_rxns), :), ...
    1:n_cond, 'un', 0));
flux_psII = cell2mat(arrayfun(@(i) ...
    sum(full(flux_psII((i-1)*numel(psII_rxns)+1:i*numel(psII_rxns), :))), ...
    1:n_cond, 'un', 0)');

% Conversion factor between flux units (mmol/gDW/h) and µmol/m2/s
fba2exp = model.lma_model(T) / 3.6;

electron_transport_pred_median = median(flux_psII * fba2exp, 2);
electron_transport_pred_mad = median(abs(flux_psII * fba2exp - electron_transport_pred_median), 2);

%% Create result table with fluxes and abundances related to the hypotheses

% Prepare result table
result_table = array2table([ ...
    median(flux_starch_synthesis, 2), ...
    median(abundances_starch_synthesis, 2), ...
    median(flux_sucrose_synthesis, 2), ...
    median(abundances_sucrose_synthesis, 2), ...
    median(flux_photorespiration, 2), ...
    median(abundances_photorespiration, 2), ...
    median(abundances_adj_pr_enyzmes, 2), ...
    median(abundances_remain_pr_enyzmes, 2), ...
    median(abundances_aox, 2), ...
    median(flux_light_reactions, 2), ...
    median(abundances_light_reactions, 2), ...
    median(abundances_core_hypoxia_proteins, 2), ...
    median(flux_core_hypoxia_rxns, 2), ...
    electron_transport_exp_mean', ...
    electron_transport_pred_median]', ...
    'RowNames', { ...
    'starch_synthesis_flux', ...
    'starch_synthesis_abundances', ...
    'sucrose_synthesis_flux', ...
    'sucrose_synthesis_abundances', ...
    'photorespiration_flux', ...
    'photorespiration_abundances', ...
    'PGP_GOX_CAT_abundances', ...
    'PR_remain_abundances', ...
    'AOX_abundances', ...
    'light_reactions_flux', ...
    'light_reactions_abundances', ...
    'core_hypoxia_abundances', ...
    'core_hypoxia_flux', ...
    'electron_transport_mean_exp', ...
    'electron_transport_median_pred'}, ...
    'VariableNames', {'210 mbar', '20 mbar', '400 mbar'});

% CSV file
writetable(result_table, ...
    fullfile(result_dir, ['results_hypotheses_' date_str '.csv']), ...
    'WriteRowNames', true)

% Excel file
writetable(result_table, ...
    fullfile(result_dir, ['results_hypotheses_' date_str '.xlsx']), ...
    'WriteRowNames', true)

end